config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get"/main" => "projects#main"

  resources :projects do
    resources :events do
      member do
        post :registration_form
      end  
    end  
  end
  resources :partners

  namespace :admin do
    resources :partners
    resources :informations
    resources :categories
    resources :projects
    resources :events do
      resources :questions 
      resources :registration_forms
      member do
        get :register_form
      end  
    end  
  end

  root :to => "projects#main"

end

app/models/event.rb
class Event < ActiveRecord::Base

  validates_presence_of :name

  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/

  belongs_to :project

  has_many  :registration_forms
  has_many  :questions, :dependent => :destroy
  has_many  :customer_answers, :dependent => :destroy

  has_many  :event_reservation_day_ships,:dependent => :destroy
  has_many  :reservation_days, :through => :event_reservation_day_ships

  def day_list
    self.reservation_days.map{ |d| d.day_info }
  end

  def day_list=(str)
    arr = str.split(",")

    self.reservation_days = arr.map do |d|
      reservation_day = ReservationRay.find_by_day_info(d)
      unless reservation_day
        reservation_day = ReservationDay.create!( :day_info => d )
      end
      reservation_day
    end
  end

  def question_list
    self.questions.map{ |q| q.content }
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController

  layout "admin"
  #後台登入
  before_action :authenticate_user!

  #檢查權限
  before_action :check_admin
  before_action :find_event, :only => [:update, :destroy, :edit, :register_form]

  def index
    @events = Event.all

    if params[:event_id]
      @event = Event.find(params[:event_id])
    else
      @event = Event.new
    end
  end

  def edit
    @event = Event.find(params[:id])
    @question = Question.new 
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      flash[:notice] = "Create Success!"
      redirect_to admin_events_path
    else
      flash[:alert] = "Create fail!"
      render "index"
    end
  end

  def update
    @event.update(event_params)
    
    if params[:destroy_logo] == "1"
        @event.logo = nil
        @event.save
    end

    if params[:event][:day_list]
      @event.reservation_days.delete_all
      day_list = params[:event][:day_list]
      day_list.shift(1)

      day_list.each do|d|
        if ReservationDay.find_by_day_info(d) == nil
          day = ReservationDay.create!(:day_info => d)
          EventReservationDayShip.create!( :event_id => @event.id, :reservation_day_id => day.id)
        elsif @event.reservation_days.find_by_day_info(d)

        else
          day =ReservationDay.find_by_day_info(d)
          EventReservationDayShip.create!( :event_id => @event.id, :reservation_day_id => day.id)
        end
      end
    end

    flash[:notice] = "Update Success!"

    if params[:prepage] =="register_form"
    end
    
    redirect_to :back
    
    
  end

  def destroy
    @event.destroy

    redirect_to admin_events_path
  end

  def register_form
  end

  private

  def event_params
    params.require(:event).permit(:project_id, :introduction,:en_introduction,
                                  :name, :en_name, :content, :en_content,
                                  :date, :time,
                                  :place,:address, :cost, :discount,
                                  :notice,:tips, :logo , :day_list
                                  )
  end   

  def find_event
    @event = Event.find(params[:id])
  end

  def check_admin
    unless current_user.admin?
        raise ActiveRecord::RecordNotFound
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :find_event, :only => [:show, :update, :destroy, :registration_form]

  def index
    @events = Event.all
    @project = Project.find(params[:project_id] )

    if params[:event_id]
      @event = Event.find(params[:event_id])
    else
      @event = Event.new
    end
  end

  def show
    @registration_form = RegistrationForm.new
  end

  def registration_form
    @registration_form = RegistrationForm.new(registration_form_params)
    @registration_form.event_id = @event.id
    
    if current_user
      @registration_form.user_id = current_user.id
    end

    if @registration_form.save
      flash[:notice] = "Create Success!"

      if @event.questions.size > 0
        @event.questions.each do |question|
          if question.answer_type == "客戶填寫"
            ans = params["question-#{question.id}"]
            create_customer_ans(question,ans)

          elsif question.answer_type == "單選"
            ans = params["question-#{question.id}"]
            create_customer_ans(question,ans)
          
          elsif question.answer_type == "多選"
            num = question.id.to_s.length
            ans =[]
            params.keys.each do |key|
              if key[0,9] == "question-" && key[9,num] == "#{question.id}"
                ans << params[key]
              end              
            end  
            create_customer_ans(question,ans)
          end
        end 
      end

      redirect_to project_event_path(:project_id => params[:project_id],:id => @event.id)
    else
      flash[:alert] = "Create fail!"
      render "show"
    end
  end

  private

  def find_event
    @event = Event.find(params[:id])
  end

  def registration_form_params
    params.require(:registration_form).permit( :event_id, :first_name,:last_name,
                                               :phone_number, :email, :people, :kids,
                                               :registed_day, :payment, :notice, :opinion,
                                               :user_id
                                              )
  end

  def create_customer_ans(question,ans)
    customer_answer = question.customer_answers.new(:registration_form_id => @registration_form.id)
    customer_answer.content = ans
    customer_answer.save
  end


end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_content_form.html.erb
<%
  if params[:event_id]
    #edit
    url = admin_event_path(@event)
  else 
    #new
    url = admin_events_path
  end
%>
<%=link_to "New", admin_events_path, :class => "btn btn-primary"%>

<%= form_for @event, :url => url do |f|%>
  <h3>內容設計</h3> 
  <hr>
  <div class="form-group">
    <%= f.label :project_id, "Project" %>
    <%= f.select :project_id, Project.all.map{ |x| [x.name, x.id]}, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :name, "name" %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :en_name, "en_name" %>
    <%= f.text_field :en_name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%=f.label :logo, "LOGO"%>
    <%=f.file_field :logo%>

    <% if @event.logo.exists? %>
      <%=image_tag(@event.logo.url(:thumb))%>
      <%= check_box_tag "destroy_logo", "1" %> 刪除檔案
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :introduction, "介紹" %>
    <%= f.text_area :introduction, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :en_introduction, "en_introduction" %>
    <%= f.text_area :en_introduction, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :content, "內容" %>
    <%= f.text_area :content, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :en_content, "en_content" %>
    <%= f.text_area :en_content, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :date, "日期" %>
    <%= f.text_area :date, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :time, "時間" %>
    <%= f.text_area :time, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :place, "集合地點" %>
    <%= f.text_field :place, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address, "地址" %>
    <%= f.text_field :address, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :cost, "價格" %>
    <%= f.text_area :cost, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :discount, "優惠" %>
    <%= f.text_area :discount, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :notice, "注意事項" %>
    <%= f.text_area :notice, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :tips, "貼心提醒" %>
    <%= f.text_area :tips, :class => "form-control" %>
  </div>
  <%= f.submit "更新",:class => "btn btn-primary" %>
<%end%>

app/views/admin/events/_register_form.html.erb
<h3>報名表設計</h3> 
<hr>
<%= form_for @event, :url => admin_event_path(@event, :prepage =>"register_form") do |f|%>
  <div class="form-group">
    <%= f.label :day_list ,"活動梯次預設"%>
    <%= f.select :day_list, ReservationDay.all.map{ |x| [x.day_info, x.day_info]}, {}, :multiple => "true" , :class => "form-control" %>
  </div>

  <%=link_to "編輯新增問題", admin_event_questions_path(@event), :class => "btn btn-warning"%>
  <br>

  <table class="table">
    <tr>
      <td>問題</td>
      <td>分類</td>
      <td>格式</td>
      <td>預設答案</td> 
    </tr>
    <% @event.questions.each do |question| %>
      <tr>
        <td><%= question.content%></td>
        <td><%= question.q_category%></td>
        <td><%= question.answer_type%></td>
        <td>
          <% question.pre_answers.each do |ans|%>
            <%=ans.a_content%>
            <br>
          <%end%>
        </td>
      </tr>
    <%end%>

  </table>

  

  <hr>

  <%= f.submit "更新",:class => "btn btn-primary" %>
<%end%>

<script>
  $("#event_day_list").select2({
     tags: <%=raw ReservationDay.all.map{ |t| t.day_info }.to_json %>,
     tokenSeparators: [',', ' ']
   });
</script>

app/views/admin/events/index.html.erb
event index

<table class="table">
  <tr>
    <td>project</td>
    <td>name</td>
    <td>date</td>
    <td>time</td>
    <td>place</td>
    <td>cost</td>
    <td>訂單</td>
    <td>編輯</td>
    <td>刪除</td>
  </tr>
  <% @events.each do |event|%>
    <tr>
      <td><%=event.project.name%></td>
      <td><%=event.name%></td>
      <td><%=event.date%></td>
      <td><%=event.time%></td>
      <td><%=event.place%></td>
      <td><%=event.cost%></td>
      <td>
        <%=link_to "訂單管理", admin_event_registration_forms_path(:event_id => event.id), :class => "btn btn-success"%>
      </td>
      <td>
        <%=link_to "內容設計", admin_events_path(:event_id => event.id), :class => "btn btn-info"%>
        <br>
        <br>
        <%=link_to "報名表設計", register_form_admin_event_path(event), :class => "btn btn-warning"%>
      </td>
      <td><%=link_to "刪除", admin_event_path(event), :method => :delete, :class => "btn btn-danger", data: { confirm: "Are you sure?"}%></td>
      <% if event.logo.exists? %>
        <td><%=image_tag(event.logo.url(:thumb))%></td>  
      <%end%>
    </tr> 
  <%end%>
</table>

<div class="clearfix"></div>

<%= render :partial => 'content_form'%>

app/views/admin/events/register_form.html.erb
<%=link_to "回上一頁", admin_events_path, :class =>"btn btn-primary btn-lg"%>
<h1>register_form</h1>

<table class="table">
  <tr>
    <td>project</td>
    <td>name</td>
    <td>date</td>
    <td>time</td>
    <td>place</td>
    <td>cost</td>
  </tr>
  
    <tr>
      <td><%=@event.project.name%></td>
      <td><%=@event.name%></td>
      <td><%=@event.date%></td>
      <td><%=@event.time%></td>
      <td><%=@event.place%></td>
      <td><%=@event.cost%></td>
</table>

<div class="clearfix"></div>

<%= render :partial => 'register_form'%>