config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get"/main" => "projects#main"

  resources :projects do
    resources :events do
      member do
        post :registration_form
      end  
    end  
  end
  resources :partners

  namespace :admin do
    resources :partners
    resources :informations
    resources :categories
    resources :projects
    resources :events do
      resources :questions 
      resources :registration_forms
      member do
        get :register_form
      end  
    end  
  end

  root :to => "projects#main"

end

app/models/partner.rb
class Partner < ActiveRecord::Base

  validates_presence_of :name, :company

  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/

  has_many :informations, :dependent => :destroy

  has_many :partner_url_ships, :dependent => :delete_all
  has_many :urls, :through => :partner_url_ships, :dependent => :delete_all

  def fb
    self.urls.find_by(:category => "fb")
  end

  def fb_url
    self.urls.find_by(:category => "fb").try(:url)
  end

  def fb_url=(str)
  end

  def blog
    self.urls.find_by(:category => "blog")
  end

  def blog_url
    self.urls.find_by(:category => "blog").try(:url)
  end

  def blog_url=(str)
  end

  def web
    self.urls.find_by(:category => "web")
  end

  def web_url
    self.urls.find_by(:category => "web").try(:url)
  end

  def web_url=(str)
  end

end

app/controllers/admin/partners_controller.rb
class Admin::PartnersController < ApplicationController

  layout "admin"
  #後台登入
  before_action :authenticate_user!

  #檢查權限
  before_action :check_admin
  before_action :find_partner, :only =>[:show, :update, :destroy]

  def index
    @partners = Partner.all
    @partner = Partner.new
  end

  def create
    @partners = Partner.all
    @partner = Partner.new(partner_params)
    
    if @partner.save
      flash[:notice] = "Create Success!"
      redirect_to admin_partners_path
    else
      flash[:alert] = "Create fail!"
      render "index"
    end

  end

  def show
    @informations = @partner.informations
    @fb_url = @partner.urls.find_by(:category => "fb").try(:url)
    @blog_url = @partner.urls.find_by(:category => "blog").try(:url)
    @web_url = @partner.urls.find_by(:category => "web").try(:url)
  end

  def update
    @partner.update(partner_params)
    flash[:notice] = "Update Success!"
    if params[:destroy_logo] == "1"
      @partner.logo = nil
      @partner.save
    end

    if partner_params[:fb_url]
      if(@partner.fb == nil)
        @url = Url.create(:url => partner_params[:fb_url], :category => "fb")
        PartnerUrlShip.create(:partner_id => @partner.id, :url_id => @url.id)
      else  
        @partner.fb.update(:url => partner_params[:fb_url])
      end
    end

    if partner_params[:blog_url]
      if(@partner.blog == nil)
        @url = Url.create(:url => partner_params[:blog_url], :category => "blog")
        PartnerUrlShip.create(:partner_id => @partner.id, :url_id => @url.id)
      else
        @partner.blog.update(:url => partner_params[:blog_url])
      end
    end

    if partner_params[:web_url]
      if(@partner.web == nil)
        @url = Url.create(:url => partner_params[:web_url], :category => "web")
        PartnerUrlShip.create(:partner_id => @partner.id, :url_id => @url.id)
      else
        @partner.web.update(:url => partner_params[:web_url])
      end
    end

    redirect_to admin_partner_path(@partner)
  end

  def destroy
    @partner.destroy

    redirect_to admin_partners_path
  end


  private

  def partner_params
    params.require(:partner).permit(:name, :company, :introduction, :my_chillchill,
                                    :en_name, :en_company, :en_introduction, :en_my_chillchill,
                                    :logo, :fb_url, :blog_url, :web_url
                                    )
  end

  def find_partner
    @partner = Partner.find(params[:id])
  end

  def check_admin
    unless current_user.admin?
        raise ActiveRecord::RecordNotFound
    end
  end

end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController

  before_action :find_partner, :only =>[:show, :update]

  def index
    @partners = Partner.all
    @partner = Partner.new
  end

  def create
    @partners = Partner.all
    @partner = Partner.new(partner_params)
    
    if @partner.save
      flash[:notice] = "Create Success!"
      redirect_to partners_path
    else
      flash[:alert] = "Create fail!"
      render "index"
    end

  end

  def show
    @informations = @partner.informations
    @fb_url = @partner.urls.find_by(:category => "fb").try(:url)
    @blog_url = @partner.urls.find_by(:category => "blog").try(:url)
    @web_url = @partner.urls.find_by(:category => "web").try(:url)
  end

  def update
    @partner.update(partner_params)
    flash[:notice] = "Update Success!"
    if params[:destroy_logo] == "1"
      @partner.logo = nil
      @partner.save
    end

    if partner_params[:fb_url]
      if(@partner.fb == nil)
        @url = Url.create(:url => partner_params[:fb_url], :category => "fb")
        PartnerUrlShip.create(:partner_id => @partner.id, :url_id => @url.id)
      else  
        @partner.fb.update(:url => partner_params[:fb_url])
      end
    end

    if partner_params[:blog_url]
      if(@partner.blog == nil)
        @url = Url.create(:url => partner_params[:blog_url], :category => "blog")
        PartnerUrlShip.create(:partner_id => @partner.id, :url_id => @url.id)
      else
        @partner.blog.update(:url => partner_params[:blog_url])
      end
    end

    if partner_params[:web_url]
      if(@partner.web == nil)
        @url = Url.create(:url => partner_params[:web_url], :category => "web")
        PartnerUrlShip.create(:partner_id => @partner.id, :url_id => @url.id)
      else
        @partner.web.update(:url => partner_params[:web_url])
      end
    end

    redirect_to partner_path(@partner)
  end

  private

  def partner_params
    params.require(:partner).permit(:name, :company, :introduction, :my_chillchill,
                                    :en_name, :en_company, :en_introduction, :en_my_chillchill,
                                    :logo, :fb_url, :blog_url, :web_url
                                    )
  end

  def find_partner
    @partner = Partner.find(params[:id])
  end

end

app/helpers/admin/partners_helper.rb
module Admin::PartnersHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/views/admin/partners/_form.html.erb
<div class="form-group">
  <%= f.label :name, "姓名" %>
  <%= f.text_field :name, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :en_name, "name" %>
  <%= f.text_field :en_name, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :company, "公司" %>
  <%= f.text_field :company, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :en_company, "compamy" %>
  <%= f.text_field :en_company, :class => "form-control" %>
</div>

<div class="form-group">
    <%=f.label :logo, "LOGO"%>
    <%=f.file_field :logo%>

    <% if @partner.logo.exists? %>
      <%= check_box_tag "destroy_logo", "1" %> 刪除檔案
    <% end %>
</div>

<%= f.submit "更新",:class => "btn btn-primary" %>

app/views/admin/partners/_partner_show.html.erb
<div class="form-group">
  <%= f.label :name, "姓名" %>
  <%= f.text_field :name, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :en_name, "name" %>
  <%= f.text_field :en_name, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :company, "公司" %>
  <%= f.text_field :company, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :en_company, "compamy" %>
  <%= f.text_field :en_company, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :introduction, "介紹" %>
  <%= f.text_area :introduction, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :en_introduction, "introduction" %>
  <%= f.text_area :en_introduction, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :my_chillchill, "Chill Chill 去去觀點" %>
  <%= f.text_area :my_chillchill, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :en_my_chillchill, "my_chillchill" %>
  <%= f.text_area :en_my_chillchill, :class => "form-control" %>
</div>

<div class="form-group">
    <%=f.label :logo, "LOGO"%>
    <%=f.file_field :logo%>

    <% if @partner.logo.exists? %>
      <%= check_box_tag "destroy_logo", "1" %> 刪除檔案
    <% end %>
</div>

<div class="form-group">
  <%= f.label :fb_url, "fb" %>
  <%= f.text_field :fb_url, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :blog_url, "blog" %>
  <%= f.text_field :blog_url, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :web_url, "web" %>
  <%= f.text_field :web_url, :class => "form-control" %>
</div>

<%= f.submit "更新",:class => "btn btn-primary" %>

app/views/admin/partners/index.html.erb
<div class="partners_title">
  <h1>chill chill partners </h1>
</div>



<% @partners.each do |p|%>
  <%= link_to admin_partner_path(p) do%>
    <div class="col-md-4 partner_block">
      <% if p.logo.exists? %>
        <%= image_tag(p.logo.url(:thumb))%>
      <%end%>
      <h3><%=p.name%></h3>
      <p><%=p.company%></p>
      <%=link_to "Delete", admin_partner_path(p),:method => :delete, :class => "btn btn-danger"%>
    </div>
  <%end%>
<%end%>


<div class="clearfix"></div>

<%= form_for @partner, :url => admin_partners_path, :method => :post do |f|%>
  <%= render :partial => 'form', :locals => { :f => f} %>
<%end%>

app/views/admin/partners/show.html.erb
<div class="partners_title">
  <h1><%=@partner.name%> </h1>
</div>
<br> 
<div class="row">
  <div class="col-md-4 partner_show_content">
    <br>
    <br>
    <%=simple_format (@partner.try(:introduction))%>
  </div>

  <div class="col-md-6 partner_show_img">
    <img src="https://static.wixstatic.com/media/a18af5_9be8230e04ab41949c24a14fe646f1ff.jpeg_srz_p_658_439_75_22_0.5_1.2_0_jpeg_srz" alt=""> 
  </div>
</div>
<br>

<div class="row">
  <div class="col-md-6 partner_show_content">
    <h3> Our Kaohsiung chill-chill </h3>
    <%=simple_format(@partner.try(:my_chillchill))%>
  </div>
</div>

<br>
<div>
  <%= link_to "節氣食旅 > > ", projects_path, :class =>"btn btn-warning btn-lg"%>
</div>
<br>
<div>
  <%= link_to "美濃微旅行 > > ", projects_path, :class =>"btn btn-success btn-lg"%>
</div>
<br>
<div>
  <%= link_to "遊船 > > ", projects_path, :class =>"btn btn-info btn-lg"%>
</div>


<hr>

<%= link_to "Edit information", admin_informations_path(:partner_id => @partner.id), :class =>"btn btn-default btn-lg"%>

<% @informations.each do |i|%>
  <ul>
    <li><%= i.company%></li>
    <li><%= i.address%></li> 
    <li><%= i.open_time%> ~ <%= i.close_time%>  Every <%= i.open_day%></li>
  </ul>  
<%end%>

<br>

<h4>
<%if @fb_url && @fb_url != ""%>
  <%= link_to "Facebook", url_for(@fb_url)%> |
<%end%>

<%if @blog_url && @blog_url != ""%>
  <%= link_to "Blog", url_for(@blog_url)%> |
<%end%>

<%if @web_url && @web_url != ""%>
  <%= link_to "Website", url_for(@web_url)%> |
<%end%>
</h4>

<hr>

<div class="clearfix"></div>

Edit partner
<%= form_for @partner, :url => admin_partner_path(@partner.id), :method => :patch do |f|%>
  <%= render :partial => 'partner_show', :locals => { :f => f} %>
<%end%>