config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get"/main" => "projects#main"

  resources :projects do
    resources :events do
      member do
        post :registration_form
      end  
    end  
  end
  resources :partners

  namespace :admin do
    resources :partners
    resources :informations
    resources :categories
    resources :projects
    resources :events do
      resources :questions 
      resources :registration_forms
      member do
        get :register_form
      end  
    end  
  end

  root :to => "projects#main"

end

app/models/project.rb
class Project < ActiveRecord::Base

  validates_presence_of :name

  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/

  has_many :category_project_ships
  has_many :categories, :through => :category_project_ships

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController

  layout "admin"

  #後台登入
  before_action :authenticate_user!

  #檢查權限
  before_action :check_admin
  before_action :find_project, :only => [:update, :destroy]

  def index
    @categories = Category.all
    @projects = Project.all

    if params[:project_id]
      @project = Project.find(params[:project_id])
    else
      @project = Project.new
    end
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = "Create Success!"
      redirect_to admin_projects_path
    else
      flash[:alert] = "Create fail!"
      render "index"
    end
  end

  def update
    @project.update(project_params)
    
    if params[:destroy_logo] == "1"
        @project.logo = nil
        @project.save
    end

    flash[:notice] = "Update Success!"
    redirect_to admin_projects_path
  end

  def destroy
    @project.destroy

    redirect_to admin_projects_path
  end



  private

  def project_params
    params.require(:project).permit(:name, :en_name,:title, :en_title, 
                                    :description,:en_description, :logo,
                                    :category_ids => []
                                  )
  end

  def find_project
    @project = Project.find(params[:id])
  end

  def check_admin
    unless current_user.admin?
        raise ActiveRecord::RecordNotFound
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def main
    @categories = Category.all
  end

  def index
    if params[:category]
      @category = Category.find(params[:category])
      @projects = @category.projects
    end
  end



end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/index.html.erb
<%@projects.each do |p|%>
  <div class="col-md-6 project_block">
    <% if p.logo.exists? %>
      <%= link_to project_events_path(:project_id => p) do%>
        <%= image_tag(p.logo.url(:thumb))%>
        <h3 class="project_name"><%=p.name%></h3>
      <%end%>
      
    <%end%>
    <h3><%=p.title%></h3>
    <%=simple_format p.description%>
  </div>
<%end%>

app/views/projects/main.html.erb
<h1>photo</h1>

<div class="col-md-6">
  <div class="subtitle col-md-12 ">
    <h3>about chill chill</h3> 
  </div>
  <div class="clearfix"></div>
  <div class="content">
    <p>
    The word “chill” delivers a comfortable, relax, and cool-fun life style of the modern generation. This exactly matches Kaohsiung, where the city style is twisting.</p>
    
    <p>Within this concept extension, chill can be pronounced and interpreted as “GO”(去) in Mandarin, to go to an unfamiliar city and enjoy a leisure wondering. Chill could also means “FUN”(趣) in Mandarin, to be involved with the locals and get to know what they are happy for open-mindedly. Moreover, we would like to boldly define chill as“PROUD”(秋) in Taiwanese. We aim to find out all the chillest parts of Kaohsiung we are proud of and share with you.</p>
  </div>

  <br>
  <br>
  <br>
  <br>

  <div class="subtitle col-md-offset-8 col-md-12">
    <h3>contact us</h3> 
  </div>
  <div class="clearfix"></div>
  <div class="content">
    <p>chillchill.kaohsiung@gmail.com</p>
    <p>+886 -953 - 555 -833 </p>
    <p>AM 12:00 - AM 18:00</p>          
  </div>

</div>

<br>
<br>
<br>

<div class="col-md-6">
  <div class="subtitle col-md-12 col-md-offset-2">
    <h3>chill chill kaohsiung project.</h3> 
  </div>
  <div class="clearfix"></div>
  <div class="content">
    <p>chill chill kaohsiung project. was founded in February 2014 . It is a field trip project to explore Kaohsiung chill-chill life style via local food, art, daily fun and nature. Our goal is to reserve old-time memory of this city while creating brand new experiences to it. This project was initiated by a group of local shops, organizations, and individuals and was from free imagination to an executive project. </p>

    <p>chill-chill partners come from various backgrounds. We're trying to leverage personal perspectives and professions to re-discover Kaohsiung and figure out the funs that convey a message or represent the iniquity of this city.  We design cool and creative local trips based on our findings. We aim to find out all the chillest parts of Kaohsiung we are proud of and share with you. </p>

    <p>There have been various fun chill-chill Kaohsiung projects tour on line. Go check it out and let us be your key access to "Kaohsiung chill-chill"!</p>  
    <br>

    <% @categories.each do|c|%>
      <div class="col-md-offset-7">
        <%= link_to "#{c.en_name} >>", main_path, :class =>"#{c.class_color(c.id)}"%>
      </div>
      <br>
    <%end%>

  </div>
  
  

</div>

<div>
  <h1>.</h1>
</div>