config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get"/main" => "projects#main"

  resources :projects do
    resources :events do
      member do
        post :registration_form
      end  
    end  
  end
  resources :partners

  namespace :admin do
    resources :partners
    resources :informations
    resources :categories
    resources :projects
    resources :events do
      resources :questions 
      resources :registration_forms
      member do
        get :register_form
      end  
    end  
  end

  root :to => "projects#main"

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/category.rb
class Category < ActiveRecord::Base

  validates_presence_of :name, :en_name

  has_many :category_project_ships
  has_many :projects, :through => :category_project_ships

  def class_color(id)
    if id%3 == 0
      "btn btn-success btn-lg"
    elsif id%3 == 2
      "btn btn-info btn-lg"
    elsif id%3 == 1
      "btn btn-warning btn-lg"
    end 
  end

end

app/models/category_project_ship.rb
class CategoryProjectShip < ActiveRecord::Base

  belongs_to :category
  belongs_to :project

end

app/models/customer_answer.rb
class CustomerAnswer < ActiveRecord::Base

  belongs_to :question
  belongs_to :registration_form

end

app/models/event.rb
class Event < ActiveRecord::Base

  validates_presence_of :name

  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/

  belongs_to :project

  has_many  :registration_forms
  has_many  :questions, :dependent => :destroy
  has_many  :customer_answers, :dependent => :destroy

  has_many  :event_reservation_day_ships,:dependent => :destroy
  has_many  :reservation_days, :through => :event_reservation_day_ships

  def day_list
    self.reservation_days.map{ |d| d.day_info }
  end

  def day_list=(str)
    arr = str.split(",")

    self.reservation_days = arr.map do |d|
      reservation_day = ReservationRay.find_by_day_info(d)
      unless reservation_day
        reservation_day = ReservationDay.create!( :day_info => d )
      end
      reservation_day
    end
  end

  def question_list
    self.questions.map{ |q| q.content }
  end

end

app/models/information.rb
class Information < ActiveRecord::Base

  belongs_to :partner

end

app/models/partner.rb
class Partner < ActiveRecord::Base

  validates_presence_of :name, :company

  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/

  has_many :informations, :dependent => :destroy

  has_many :partner_url_ships, :dependent => :delete_all
  has_many :urls, :through => :partner_url_ships, :dependent => :delete_all

  def fb
    self.urls.find_by(:category => "fb")
  end

  def fb_url
    self.urls.find_by(:category => "fb").try(:url)
  end

  def fb_url=(str)
  end

  def blog
    self.urls.find_by(:category => "blog")
  end

  def blog_url
    self.urls.find_by(:category => "blog").try(:url)
  end

  def blog_url=(str)
  end

  def web
    self.urls.find_by(:category => "web")
  end

  def web_url
    self.urls.find_by(:category => "web").try(:url)
  end

  def web_url=(str)
  end

end

app/models/partner_url_ship.rb
class PartnerUrlShip < ActiveRecord::Base

  belongs_to :partner
  belongs_to :url

end

app/models/pre_answer.rb
class PreAnswer < ActiveRecord::Base

  has_many  :question_pre_answer_ships
  has_many  :questions, :through => :question_pre_answer_ships
end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base

  validates_presence_of :name

  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/

  has_many :category_project_ships
  has_many :categories, :through => :category_project_ships

end

app/models/question.rb
class Question < ActiveRecord::Base
  
  validates_presence_of :content, :answer_type

  belongs_to :event

  has_many  :question_pre_answer_ships,:dependent => :destroy
  has_many  :pre_answers, :through => :question_pre_answer_ships

  has_many  :customer_answers

  def pre_answer
    self.pre_answers.map{ |d| d.a_content }
  end

  def pre_answer=(str)
    arr = str.split(",")

    self.pre_answers = arr.map do |d|
      pre_answer = PreAnswer.find_by_a_content(d)
      unless pre_answer
        pre_answer = PreAnswer.create!( :a_content => d )
      end
      pre_answer
    end
  end
end

app/models/registration_form.rb
class RegistrationForm < ActiveRecord::Base

  validates_presence_of :first_name, :phone_number, :email, :people, :payment ,:message => "請確認 * 必填"
  validates_length_of :first_name, :minimum => 2
  validates_numericality_of :phone_number,:people, :only_integer => true
  validates_format_of :email, :with => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  
  belongs_to :event
  has_many  :customer_answers

  def day_list(event)
    event.reservation_days.map{ |d| d.day_info }
  end

  def day_list=(str)
    arr = str.split(",")

    self.reservation_days = arr.map do |d|
      reservation_day = ReservationRay.find_by_day_info(d)
      unless reservation_day
        reservation_day = ReservationDay.create!( :day_info => d )
      end
      reservation_day
    end
  end
  
end

app/models/reservation_day.rb
class ReservationDay < ActiveRecord::Base

  has_many  :event_reservation_day_ships
  has_many  :events, :through => :event_reservation_day_ships

end

app/models/url.rb
class Url < ActiveRecord::Base

  has_many :partner_url_ships
  has_many :partners, :through => :partner_url_ships

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_one :profile, dependent: :destroy

  after_create :create_profile

  def admin?
    self.role == "admin"
  end

  def create_profile
    self.build_profile
    self.profile.save!
    self.profile
  end

  def self.from_omniauth(auth)
      # Case 1: Find existing user by facebook uid
    user = User.find_by_fb_uid( auth.uid )
    if user
      user.fb_token = auth.credentials.token
    #   user.fb_raw_data = auth
      user.save!
      return user
    end

    # Case 2: Find existing user by email
    existing_user = User.find_by_email( auth.info.email )
    if existing_user
      existing_user.fb_uid = auth.uid
      existing_user.fb_token = auth.credentials.token
      #existing_user.fb_raw_data = auth
      existing_user.save!
      return existing_user
    end

    # Case 3: Create new password

    user = User.new
    user.fb_uid = auth.uid
    user.fb_token = auth.credentials.token
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.fb_raw_data = auth
    user.role ="normal"
    user.save!
    
    profile = user.create_profile
    profile.username = auth.info.name
    profile.first_name = auth.info.first_name
    profile.last_name = auth.info.last_name
    profile.birthday = auth.extra.raw_info.birthday
    profile.location = auth.info.location
    profile.locale = auth.extra.raw_info.locale
    profile.gender = auth.extra.raw_info.gender

    edu_array =[]    
    auth.extra.raw_info.education.each do |education|
      if education.try(:concentration)
        edu_array << education.school.name + education.concentration[0].name
      else 
        edu_array << education.school.name
      end
      profile.education = edu_array
    end

    profile.fb_image = auth.info.image
    profile.save!

    return user
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chillchill</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="col-md-offset-10">
      <p> En|中 </p>
      <p><%= link_to "admin", admin_events_path%></p>
      <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), :class => "btn btn-info" %>
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %> 
    </div>
    <% if flash[:notice].present? %>
      <div style = "color: green" class="col-md-offset-3">
        <h1><%= flash[:notice]%></h1> 
      </div>
    <% end %>

    <% if flash[:alert].present? %>
      <div style = "color: red" class="col-md-offset-3">
        <h1><%= flash[:alert]%></h1> 
      </div>
    <% end %>

    
  </div>
</div>

<br>  
<br>
<br>

<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2" id="title">
        <div class="col-md-10">
          <div class="row ">
            <div class="col-md-12">
              <h1>
                <%=link_to "chill chill kaohsiung project.", main_path%></h1>
            </div>
          </div>
          <div class="row"> 
            <div class="col-md-10">
              <h5><%= link_to "a field trip project to explore Kaohsiung chill-chill lifestyle via local food, art, life, daily fun, and nature",main_path %></h5>
            </div>
          </div>
        </div>

        <div class="col-md-2">
          <h2 id="title2">
            <%= link_to "去 去 高 雄", main_path%></h2>
        </div>
        <br>
    </div>
  </div>

  <h5>.</h5>
  
  <div class="row">
    <div class="col-md-9 col-md-offset-2" id="banner-link">
      <div class="table">
        <tr>
          <td><%= link_to "admin category", admin_categories_path%></td>
        </tr>
        <br>
        <tr>
          <td><%= link_to "admin project", admin_projects_path%></td>
        </tr>
        <br>
        <tr>
          <td><%= link_to "admin event", admin_events_path%></td>
        </tr>
        <br>
        <tr>
          <td><%= link_to "admin food adventure"%></td>
          <td><%= link_to "admin outdoor fun"%></td>
          <td><%= link_to "admin local partner", admin_partners_path%></td>
          <td><%= link_to "admin reservation"%></td>
          <td>
            <a href="https://www.facebook.com/chillchillkaohsiung"><i class="fa fa-facebook"></i></a>  
          </td>
          <td>
            <a href="http://instagram.com/chillchillkh"><i class="fa fa-instagram"></i></a>
          </td>
          <td>
            <a href="http://www.tripadvisor.com.tw/Attraction_Review-g297908-d6847667-Reviews-Chill_chill_Kaohsiung_project_Food_Tours_and_Taiwanese_Cooking_Class-Kaohsiung.html"><i class="fa fa-tripadvisor"></i></a>
          </td>
        </tr>
    </div>
  </div> 

  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <%= yield %>
    </div>
  </div>
</div>



</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chillchill</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <meta property="og:url"           content="http://localhost:3000/partners/1" />
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="去去高雄｜ chill chill kaohsiung project. ｜ local tour ｜ cooking class" />
  <meta property="og:description"   content="高雄,廚藝教室,有機市集,體驗,料理,做菜,農夫市集,料理教室,美濃,好吃,品茶,品茗,攀岩,探洞,騎單車,旅遊觀光,愛河,節氣食旅,背包客,特殊體驗,創意,旅行,設計,風格城市,港都,駁二,酷玩,有趣,輕鬆快活,小旅行廚房,ki厝,郭銘哲,chez kiki,微風市集,勇氣廚房,李建達,agnes甜點,雄好呷" />
  <meta property="og:image"         content="http://img1.wikia.nocookie.net/__cb20110105015923/ranmafanon/images/c/c7/Jnh_hj_hj_bhj_bhbj_hbj.jpg" />
</head>
<body>

<div class="container">
  <div class="row">
    <div class="col-md-10">
      <% if flash[:notice].present? %>
        <div style = "color: green" class="col-md-offset-3">
          <h3><%= flash[:notice]%></h3> 
        </div>
      <% end %>

      <% if flash[:alert].present? %>
        <div style = "color: red" class="col-md-offset-3">
          <h3><%= flash[:alert]%></h3> 
        </div>
      <% end %>
    </div>
    <div class="col-md-offset-10">
      <p> En|中 </p>
      <%if current_user && current_user.admin?%>  
        <p><%= link_to "admin", admin_events_path%></p>
      <%end%>
    </div>
  </div>
</div>

<br>

<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2" id="title">
        <div class="col-md-10">
          <div class="row ">
            <div class="col-md-12">
              <h1>
                <%=link_to "chill chill kaohsiung project.", main_path%></h1>
            </div>
          </div>
          <div class="row"> 
            <div class="col-md-10">
              <h5><%= link_to "a field trip project to explore Kaohsiung chill-chill lifestyle via local food, art, life, daily fun, and nature",main_path %></h5>
            </div>
          </div>
        </div>

        <div class="col-md-2">
          <h2 id="title2">
            <%= link_to "去 去 高 雄", main_path%></h2>
        </div>
        <br>
    </div>
    <div class="col-2">
      <%if current_user%>
        <h3>
        Hello! <%= image_tag (current_user.profile.fb_image), style: "width: 40px; height: 40px; display: inline; border-radius: 20px;" %> <%= current_user.profile.first_name || current_user.profile.username%>
        </h3>
        <br>
        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %> 
      <%else%>
        <%= link_to user_omniauth_authorize_path(:facebook), :class => "btn btn-primary" do%>
            <i class="fa fa-facebook-square"> Sign in with Facebook </i>
        <%end%>
      <%end%>
    </div>
  </div>

  <h5>.</h5>
  
  <div class="row">
    <div class="col-md-9 col-md-offset-2" id="banner-link">
      <div class="table" id="outlink-icon">
        <tr>
          <% Category.all.each do |c|%>
            <td><%= link_to c.name, projects_path(:category => c.id)%></td>
          <%end%>
          <td><%= link_to "local partner", partners_path%></td>
          <td><%= link_to "reservation"%></td>
          <td>
            <a href="https://www.facebook.com/chillchillkaohsiung"><i class="fa fa-facebook"></i></a>  
          </td>
          <td>
            <a href="http://instagram.com/chillchillkh"><i class="fa fa-instagram"></i></a>
          </td>
          <td>
            <a href="http://www.tripadvisor.com.tw/Attraction_Review-g297908-d6847667-Reviews-Chill_chill_Kaohsiung_project_Food_Tours_and_Taiwanese_Cooking_Class-Kaohsiung.html"><i class="fa fa-tripadvisor"></i></a>
          </td>
        </tr>
    </div>
  </div> 

  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <%= yield %>
    </div>
  </div>
</div>

<div id="fb-root"></div>
<script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "//connect.facebook.net/zh_TW/sdk.js#xfbml=1&version=v2.5&appId=563223240506725";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


</body>
</html>